---
name: build 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  compile-coq-proof:
    runs-on: ubuntu-latest  # container actions require GNU/Linux
    strategy:
      matrix:
        coq_version:
          - '8.13.2'
          - '8.16'
          - dev
        ocaml_version: ['default']
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          script: sudo make
