---
name: build 
on: [push, pull_request]
jobs:
  compile-coq-proof:
    runs-on: ubuntu-latest  # container actions require GNU/Linux
    strategy:
      matrix:
        coq_version:
          - '8.16'
        ocaml_version: ['default']
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          install: |
            startGroup "Install dependencies"
              cd ../
              pwd
              ls -al
              sudo apt-get update -y -q
              opam pin add -n -y -k path $PACKAGE $WORKDIR

              opam update -y
              opam install --confirm-level=unsafe-yes -j 2 $PACKAGE --deps-only
            endGroup
          opam_file: "fixismu-coq.opam"
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          after_script: |
            set -o pipefail

            startGroup "Check context summary"
              pwd
              ls
              coqchk -R . FaComp2 -silent -o FaComp2.FullAbstractionFI FaComp2.FullAbstractionFE FaComp2.FullAbstractionIE 2>&1 | diff context_summary.txt -
            endGroup
